---
title: "ggplot2"
author: "Sophia"
date: "2020/7/8"
output: pdf_document
---
Learn data visulization with 'ggplot2'.
```{r setup,include=FALSE}
library(tidyverse)
library(MASS)
library(conflicted)
conflict_prefer("select","dplyr")

```

```{r, message = F}
#National Parks in California
ca <- read_csv("data/ca.csv") 

#Acadia National Park
acadia <- read_csv("data/acadia.csv")

#Southeast US National Parks
se <- read_csv("data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("data/mass.csv")
```

```
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <COORDINATE_FUNCTION> +
  <FACET_FUNCTION>
```
```{r}
head(ca)
ggplot(data=ca) +
  geom_point(aes(x = year, y = visitors))
```

```{r, eval = F}
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name))
```
```{r, eval = F}
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name)) +
    labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
    theme_bw() +
    theme(legend.title=element_blank())
```
```{r, eval = F}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors)) +
    facet_wrap(~ state)
```
```{r, eval = F}
ggplot(data = se) +
     geom_point(aes(x = year, y = visitors, color = park_name)) +
     facet_wrap(~ state, scales = "free")
```
```{r, eval = F}
ggplot(data = se) + 
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), 
              width = 0.1, 
              alpha = 0.4) +
  coord_flip() +
  theme(legend.position = "none") 
```
```{r}
gapminder <- read_csv('data/gapminder.csv') 
view(gapminder)
```

